// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: csv/CSVRecords.proto

package csv;

public final class csvproto {
  private csvproto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface CSVDataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:csv.CSVData)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string name = 1;</code>
     */
    boolean hasName();
    /**
     * <code>required string name = 1;</code>
     */
    java.lang.String getName();
    /**
     * <code>required string name = 1;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>required string city = 2;</code>
     */
    boolean hasCity();
    /**
     * <code>required string city = 2;</code>
     */
    java.lang.String getCity();
    /**
     * <code>required string city = 2;</code>
     */
    com.google.protobuf.ByteString
        getCityBytes();

    /**
     * <code>optional string address = 3;</code>
     */
    boolean hasAddress();
    /**
     * <code>optional string address = 3;</code>
     */
    java.lang.String getAddress();
    /**
     * <code>optional string address = 3;</code>
     */
    com.google.protobuf.ByteString
        getAddressBytes();

    /**
     * <code>required int32 age = 4;</code>
     */
    boolean hasAge();
    /**
     * <code>required int32 age = 4;</code>
     */
    int getAge();

    /**
     * <code>optional string city2 = 5;</code>
     */
    boolean hasCity2();
    /**
     * <code>optional string city2 = 5;</code>
     */
    java.lang.String getCity2();
    /**
     * <code>optional string city2 = 5;</code>
     */
    com.google.protobuf.ByteString
        getCity2Bytes();

    /**
     * <code>required string zipcode = 6;</code>
     */
    boolean hasZipcode();
    /**
     * <code>required string zipcode = 6;</code>
     */
    java.lang.String getZipcode();
    /**
     * <code>required string zipcode = 6;</code>
     */
    com.google.protobuf.ByteString
        getZipcodeBytes();
  }
  /**
   * Protobuf type {@code csv.CSVData}
   */
  public  static final class CSVData extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:csv.CSVData)
      CSVDataOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CSVData.newBuilder() to construct.
    private CSVData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CSVData() {
      name_ = "";
      city_ = "";
      address_ = "";
      age_ = 0;
      city2_ = "";
      zipcode_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private CSVData(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              name_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              city_ = bs;
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              address_ = bs;
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              age_ = input.readInt32();
              break;
            }
            case 42: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000010;
              city2_ = bs;
              break;
            }
            case 50: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000020;
              zipcode_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return csv.csvproto.internal_static_csv_CSVData_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return csv.csvproto.internal_static_csv_CSVData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              csv.csvproto.CSVData.class, csv.csvproto.CSVData.Builder.class);
    }

    private int bitField0_;
    public static final int NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object name_;
    /**
     * <code>required string name = 1;</code>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string name = 1;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CITY_FIELD_NUMBER = 2;
    private volatile java.lang.Object city_;
    /**
     * <code>required string city = 2;</code>
     */
    public boolean hasCity() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string city = 2;</code>
     */
    public java.lang.String getCity() {
      java.lang.Object ref = city_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          city_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string city = 2;</code>
     */
    public com.google.protobuf.ByteString
        getCityBytes() {
      java.lang.Object ref = city_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        city_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ADDRESS_FIELD_NUMBER = 3;
    private volatile java.lang.Object address_;
    /**
     * <code>optional string address = 3;</code>
     */
    public boolean hasAddress() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string address = 3;</code>
     */
    public java.lang.String getAddress() {
      java.lang.Object ref = address_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          address_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string address = 3;</code>
     */
    public com.google.protobuf.ByteString
        getAddressBytes() {
      java.lang.Object ref = address_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        address_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int AGE_FIELD_NUMBER = 4;
    private int age_;
    /**
     * <code>required int32 age = 4;</code>
     */
    public boolean hasAge() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required int32 age = 4;</code>
     */
    public int getAge() {
      return age_;
    }

    public static final int CITY2_FIELD_NUMBER = 5;
    private volatile java.lang.Object city2_;
    /**
     * <code>optional string city2 = 5;</code>
     */
    public boolean hasCity2() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional string city2 = 5;</code>
     */
    public java.lang.String getCity2() {
      java.lang.Object ref = city2_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          city2_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string city2 = 5;</code>
     */
    public com.google.protobuf.ByteString
        getCity2Bytes() {
      java.lang.Object ref = city2_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        city2_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ZIPCODE_FIELD_NUMBER = 6;
    private volatile java.lang.Object zipcode_;
    /**
     * <code>required string zipcode = 6;</code>
     */
    public boolean hasZipcode() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>required string zipcode = 6;</code>
     */
    public java.lang.String getZipcode() {
      java.lang.Object ref = zipcode_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          zipcode_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string zipcode = 6;</code>
     */
    public com.google.protobuf.ByteString
        getZipcodeBytes() {
      java.lang.Object ref = zipcode_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        zipcode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCity()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasAge()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasZipcode()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, city_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, address_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, age_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, city2_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, zipcode_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, city_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, address_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, age_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, city2_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, zipcode_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof csv.csvproto.CSVData)) {
        return super.equals(obj);
      }
      csv.csvproto.CSVData other = (csv.csvproto.CSVData) obj;

      boolean result = true;
      result = result && (hasName() == other.hasName());
      if (hasName()) {
        result = result && getName()
            .equals(other.getName());
      }
      result = result && (hasCity() == other.hasCity());
      if (hasCity()) {
        result = result && getCity()
            .equals(other.getCity());
      }
      result = result && (hasAddress() == other.hasAddress());
      if (hasAddress()) {
        result = result && getAddress()
            .equals(other.getAddress());
      }
      result = result && (hasAge() == other.hasAge());
      if (hasAge()) {
        result = result && (getAge()
            == other.getAge());
      }
      result = result && (hasCity2() == other.hasCity2());
      if (hasCity2()) {
        result = result && getCity2()
            .equals(other.getCity2());
      }
      result = result && (hasZipcode() == other.hasZipcode());
      if (hasZipcode()) {
        result = result && getZipcode()
            .equals(other.getZipcode());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasName()) {
        hash = (37 * hash) + NAME_FIELD_NUMBER;
        hash = (53 * hash) + getName().hashCode();
      }
      if (hasCity()) {
        hash = (37 * hash) + CITY_FIELD_NUMBER;
        hash = (53 * hash) + getCity().hashCode();
      }
      if (hasAddress()) {
        hash = (37 * hash) + ADDRESS_FIELD_NUMBER;
        hash = (53 * hash) + getAddress().hashCode();
      }
      if (hasAge()) {
        hash = (37 * hash) + AGE_FIELD_NUMBER;
        hash = (53 * hash) + getAge();
      }
      if (hasCity2()) {
        hash = (37 * hash) + CITY2_FIELD_NUMBER;
        hash = (53 * hash) + getCity2().hashCode();
      }
      if (hasZipcode()) {
        hash = (37 * hash) + ZIPCODE_FIELD_NUMBER;
        hash = (53 * hash) + getZipcode().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static csv.csvproto.CSVData parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static csv.csvproto.CSVData parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static csv.csvproto.CSVData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static csv.csvproto.CSVData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static csv.csvproto.CSVData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static csv.csvproto.CSVData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static csv.csvproto.CSVData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static csv.csvproto.CSVData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static csv.csvproto.CSVData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static csv.csvproto.CSVData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static csv.csvproto.CSVData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static csv.csvproto.CSVData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(csv.csvproto.CSVData prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code csv.CSVData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:csv.CSVData)
        csv.csvproto.CSVDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return csv.csvproto.internal_static_csv_CSVData_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return csv.csvproto.internal_static_csv_CSVData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                csv.csvproto.CSVData.class, csv.csvproto.CSVData.Builder.class);
      }

      // Construct using csv.csvproto.CSVData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        city_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        address_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        age_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        city2_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        zipcode_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return csv.csvproto.internal_static_csv_CSVData_descriptor;
      }

      public csv.csvproto.CSVData getDefaultInstanceForType() {
        return csv.csvproto.CSVData.getDefaultInstance();
      }

      public csv.csvproto.CSVData build() {
        csv.csvproto.CSVData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public csv.csvproto.CSVData buildPartial() {
        csv.csvproto.CSVData result = new csv.csvproto.CSVData(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.city_ = city_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.address_ = address_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.age_ = age_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.city2_ = city2_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.zipcode_ = zipcode_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof csv.csvproto.CSVData) {
          return mergeFrom((csv.csvproto.CSVData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(csv.csvproto.CSVData other) {
        if (other == csv.csvproto.CSVData.getDefaultInstance()) return this;
        if (other.hasName()) {
          bitField0_ |= 0x00000001;
          name_ = other.name_;
          onChanged();
        }
        if (other.hasCity()) {
          bitField0_ |= 0x00000002;
          city_ = other.city_;
          onChanged();
        }
        if (other.hasAddress()) {
          bitField0_ |= 0x00000004;
          address_ = other.address_;
          onChanged();
        }
        if (other.hasAge()) {
          setAge(other.getAge());
        }
        if (other.hasCity2()) {
          bitField0_ |= 0x00000010;
          city2_ = other.city2_;
          onChanged();
        }
        if (other.hasZipcode()) {
          bitField0_ |= 0x00000020;
          zipcode_ = other.zipcode_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasName()) {
          return false;
        }
        if (!hasCity()) {
          return false;
        }
        if (!hasAge()) {
          return false;
        }
        if (!hasZipcode()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        csv.csvproto.CSVData parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (csv.csvproto.CSVData) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object name_ = "";
      /**
       * <code>required string name = 1;</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string name = 1;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            name_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string name = 1;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 1;</code>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 1;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object city_ = "";
      /**
       * <code>required string city = 2;</code>
       */
      public boolean hasCity() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string city = 2;</code>
       */
      public java.lang.String getCity() {
        java.lang.Object ref = city_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            city_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string city = 2;</code>
       */
      public com.google.protobuf.ByteString
          getCityBytes() {
        java.lang.Object ref = city_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          city_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string city = 2;</code>
       */
      public Builder setCity(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        city_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string city = 2;</code>
       */
      public Builder clearCity() {
        bitField0_ = (bitField0_ & ~0x00000002);
        city_ = getDefaultInstance().getCity();
        onChanged();
        return this;
      }
      /**
       * <code>required string city = 2;</code>
       */
      public Builder setCityBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        city_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object address_ = "";
      /**
       * <code>optional string address = 3;</code>
       */
      public boolean hasAddress() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string address = 3;</code>
       */
      public java.lang.String getAddress() {
        java.lang.Object ref = address_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            address_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string address = 3;</code>
       */
      public com.google.protobuf.ByteString
          getAddressBytes() {
        java.lang.Object ref = address_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          address_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string address = 3;</code>
       */
      public Builder setAddress(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        address_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string address = 3;</code>
       */
      public Builder clearAddress() {
        bitField0_ = (bitField0_ & ~0x00000004);
        address_ = getDefaultInstance().getAddress();
        onChanged();
        return this;
      }
      /**
       * <code>optional string address = 3;</code>
       */
      public Builder setAddressBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        address_ = value;
        onChanged();
        return this;
      }

      private int age_ ;
      /**
       * <code>required int32 age = 4;</code>
       */
      public boolean hasAge() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required int32 age = 4;</code>
       */
      public int getAge() {
        return age_;
      }
      /**
       * <code>required int32 age = 4;</code>
       */
      public Builder setAge(int value) {
        bitField0_ |= 0x00000008;
        age_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 age = 4;</code>
       */
      public Builder clearAge() {
        bitField0_ = (bitField0_ & ~0x00000008);
        age_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object city2_ = "";
      /**
       * <code>optional string city2 = 5;</code>
       */
      public boolean hasCity2() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional string city2 = 5;</code>
       */
      public java.lang.String getCity2() {
        java.lang.Object ref = city2_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            city2_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string city2 = 5;</code>
       */
      public com.google.protobuf.ByteString
          getCity2Bytes() {
        java.lang.Object ref = city2_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          city2_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string city2 = 5;</code>
       */
      public Builder setCity2(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        city2_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string city2 = 5;</code>
       */
      public Builder clearCity2() {
        bitField0_ = (bitField0_ & ~0x00000010);
        city2_ = getDefaultInstance().getCity2();
        onChanged();
        return this;
      }
      /**
       * <code>optional string city2 = 5;</code>
       */
      public Builder setCity2Bytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        city2_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object zipcode_ = "";
      /**
       * <code>required string zipcode = 6;</code>
       */
      public boolean hasZipcode() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>required string zipcode = 6;</code>
       */
      public java.lang.String getZipcode() {
        java.lang.Object ref = zipcode_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            zipcode_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string zipcode = 6;</code>
       */
      public com.google.protobuf.ByteString
          getZipcodeBytes() {
        java.lang.Object ref = zipcode_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          zipcode_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string zipcode = 6;</code>
       */
      public Builder setZipcode(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        zipcode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string zipcode = 6;</code>
       */
      public Builder clearZipcode() {
        bitField0_ = (bitField0_ & ~0x00000020);
        zipcode_ = getDefaultInstance().getZipcode();
        onChanged();
        return this;
      }
      /**
       * <code>required string zipcode = 6;</code>
       */
      public Builder setZipcodeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        zipcode_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:csv.CSVData)
    }

    // @@protoc_insertion_point(class_scope:csv.CSVData)
    private static final csv.csvproto.CSVData DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new csv.csvproto.CSVData();
    }

    public static csv.csvproto.CSVData getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<CSVData>
        PARSER = new com.google.protobuf.AbstractParser<CSVData>() {
      public CSVData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CSVData(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CSVData> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CSVData> getParserForType() {
      return PARSER;
    }

    public csv.csvproto.CSVData getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface CSVDataHouseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:csv.CSVDataHouse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .csv.CSVData csvdata = 1;</code>
     */
    java.util.List<csv.csvproto.CSVData> 
        getCsvdataList();
    /**
     * <code>repeated .csv.CSVData csvdata = 1;</code>
     */
    csv.csvproto.CSVData getCsvdata(int index);
    /**
     * <code>repeated .csv.CSVData csvdata = 1;</code>
     */
    int getCsvdataCount();
    /**
     * <code>repeated .csv.CSVData csvdata = 1;</code>
     */
    java.util.List<? extends csv.csvproto.CSVDataOrBuilder> 
        getCsvdataOrBuilderList();
    /**
     * <code>repeated .csv.CSVData csvdata = 1;</code>
     */
    csv.csvproto.CSVDataOrBuilder getCsvdataOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code csv.CSVDataHouse}
   */
  public  static final class CSVDataHouse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:csv.CSVDataHouse)
      CSVDataHouseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CSVDataHouse.newBuilder() to construct.
    private CSVDataHouse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CSVDataHouse() {
      csvdata_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private CSVDataHouse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                csvdata_ = new java.util.ArrayList<csv.csvproto.CSVData>();
                mutable_bitField0_ |= 0x00000001;
              }
              csvdata_.add(
                  input.readMessage(csv.csvproto.CSVData.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          csvdata_ = java.util.Collections.unmodifiableList(csvdata_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return csv.csvproto.internal_static_csv_CSVDataHouse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return csv.csvproto.internal_static_csv_CSVDataHouse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              csv.csvproto.CSVDataHouse.class, csv.csvproto.CSVDataHouse.Builder.class);
    }

    public static final int CSVDATA_FIELD_NUMBER = 1;
    private java.util.List<csv.csvproto.CSVData> csvdata_;
    /**
     * <code>repeated .csv.CSVData csvdata = 1;</code>
     */
    public java.util.List<csv.csvproto.CSVData> getCsvdataList() {
      return csvdata_;
    }
    /**
     * <code>repeated .csv.CSVData csvdata = 1;</code>
     */
    public java.util.List<? extends csv.csvproto.CSVDataOrBuilder> 
        getCsvdataOrBuilderList() {
      return csvdata_;
    }
    /**
     * <code>repeated .csv.CSVData csvdata = 1;</code>
     */
    public int getCsvdataCount() {
      return csvdata_.size();
    }
    /**
     * <code>repeated .csv.CSVData csvdata = 1;</code>
     */
    public csv.csvproto.CSVData getCsvdata(int index) {
      return csvdata_.get(index);
    }
    /**
     * <code>repeated .csv.CSVData csvdata = 1;</code>
     */
    public csv.csvproto.CSVDataOrBuilder getCsvdataOrBuilder(
        int index) {
      return csvdata_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      for (int i = 0; i < getCsvdataCount(); i++) {
        if (!getCsvdata(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < csvdata_.size(); i++) {
        output.writeMessage(1, csvdata_.get(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < csvdata_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, csvdata_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof csv.csvproto.CSVDataHouse)) {
        return super.equals(obj);
      }
      csv.csvproto.CSVDataHouse other = (csv.csvproto.CSVDataHouse) obj;

      boolean result = true;
      result = result && getCsvdataList()
          .equals(other.getCsvdataList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getCsvdataCount() > 0) {
        hash = (37 * hash) + CSVDATA_FIELD_NUMBER;
        hash = (53 * hash) + getCsvdataList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static csv.csvproto.CSVDataHouse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static csv.csvproto.CSVDataHouse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static csv.csvproto.CSVDataHouse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static csv.csvproto.CSVDataHouse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static csv.csvproto.CSVDataHouse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static csv.csvproto.CSVDataHouse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static csv.csvproto.CSVDataHouse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static csv.csvproto.CSVDataHouse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static csv.csvproto.CSVDataHouse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static csv.csvproto.CSVDataHouse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static csv.csvproto.CSVDataHouse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static csv.csvproto.CSVDataHouse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(csv.csvproto.CSVDataHouse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code csv.CSVDataHouse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:csv.CSVDataHouse)
        csv.csvproto.CSVDataHouseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return csv.csvproto.internal_static_csv_CSVDataHouse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return csv.csvproto.internal_static_csv_CSVDataHouse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                csv.csvproto.CSVDataHouse.class, csv.csvproto.CSVDataHouse.Builder.class);
      }

      // Construct using csv.csvproto.CSVDataHouse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getCsvdataFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (csvdataBuilder_ == null) {
          csvdata_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          csvdataBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return csv.csvproto.internal_static_csv_CSVDataHouse_descriptor;
      }

      public csv.csvproto.CSVDataHouse getDefaultInstanceForType() {
        return csv.csvproto.CSVDataHouse.getDefaultInstance();
      }

      public csv.csvproto.CSVDataHouse build() {
        csv.csvproto.CSVDataHouse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public csv.csvproto.CSVDataHouse buildPartial() {
        csv.csvproto.CSVDataHouse result = new csv.csvproto.CSVDataHouse(this);
        int from_bitField0_ = bitField0_;
        if (csvdataBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            csvdata_ = java.util.Collections.unmodifiableList(csvdata_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.csvdata_ = csvdata_;
        } else {
          result.csvdata_ = csvdataBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof csv.csvproto.CSVDataHouse) {
          return mergeFrom((csv.csvproto.CSVDataHouse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(csv.csvproto.CSVDataHouse other) {
        if (other == csv.csvproto.CSVDataHouse.getDefaultInstance()) return this;
        if (csvdataBuilder_ == null) {
          if (!other.csvdata_.isEmpty()) {
            if (csvdata_.isEmpty()) {
              csvdata_ = other.csvdata_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureCsvdataIsMutable();
              csvdata_.addAll(other.csvdata_);
            }
            onChanged();
          }
        } else {
          if (!other.csvdata_.isEmpty()) {
            if (csvdataBuilder_.isEmpty()) {
              csvdataBuilder_.dispose();
              csvdataBuilder_ = null;
              csvdata_ = other.csvdata_;
              bitField0_ = (bitField0_ & ~0x00000001);
              csvdataBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getCsvdataFieldBuilder() : null;
            } else {
              csvdataBuilder_.addAllMessages(other.csvdata_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        for (int i = 0; i < getCsvdataCount(); i++) {
          if (!getCsvdata(i).isInitialized()) {
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        csv.csvproto.CSVDataHouse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (csv.csvproto.CSVDataHouse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<csv.csvproto.CSVData> csvdata_ =
        java.util.Collections.emptyList();
      private void ensureCsvdataIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          csvdata_ = new java.util.ArrayList<csv.csvproto.CSVData>(csvdata_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          csv.csvproto.CSVData, csv.csvproto.CSVData.Builder, csv.csvproto.CSVDataOrBuilder> csvdataBuilder_;

      /**
       * <code>repeated .csv.CSVData csvdata = 1;</code>
       */
      public java.util.List<csv.csvproto.CSVData> getCsvdataList() {
        if (csvdataBuilder_ == null) {
          return java.util.Collections.unmodifiableList(csvdata_);
        } else {
          return csvdataBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .csv.CSVData csvdata = 1;</code>
       */
      public int getCsvdataCount() {
        if (csvdataBuilder_ == null) {
          return csvdata_.size();
        } else {
          return csvdataBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .csv.CSVData csvdata = 1;</code>
       */
      public csv.csvproto.CSVData getCsvdata(int index) {
        if (csvdataBuilder_ == null) {
          return csvdata_.get(index);
        } else {
          return csvdataBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .csv.CSVData csvdata = 1;</code>
       */
      public Builder setCsvdata(
          int index, csv.csvproto.CSVData value) {
        if (csvdataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCsvdataIsMutable();
          csvdata_.set(index, value);
          onChanged();
        } else {
          csvdataBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .csv.CSVData csvdata = 1;</code>
       */
      public Builder setCsvdata(
          int index, csv.csvproto.CSVData.Builder builderForValue) {
        if (csvdataBuilder_ == null) {
          ensureCsvdataIsMutable();
          csvdata_.set(index, builderForValue.build());
          onChanged();
        } else {
          csvdataBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .csv.CSVData csvdata = 1;</code>
       */
      public Builder addCsvdata(csv.csvproto.CSVData value) {
        if (csvdataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCsvdataIsMutable();
          csvdata_.add(value);
          onChanged();
        } else {
          csvdataBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .csv.CSVData csvdata = 1;</code>
       */
      public Builder addCsvdata(
          int index, csv.csvproto.CSVData value) {
        if (csvdataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCsvdataIsMutable();
          csvdata_.add(index, value);
          onChanged();
        } else {
          csvdataBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .csv.CSVData csvdata = 1;</code>
       */
      public Builder addCsvdata(
          csv.csvproto.CSVData.Builder builderForValue) {
        if (csvdataBuilder_ == null) {
          ensureCsvdataIsMutable();
          csvdata_.add(builderForValue.build());
          onChanged();
        } else {
          csvdataBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .csv.CSVData csvdata = 1;</code>
       */
      public Builder addCsvdata(
          int index, csv.csvproto.CSVData.Builder builderForValue) {
        if (csvdataBuilder_ == null) {
          ensureCsvdataIsMutable();
          csvdata_.add(index, builderForValue.build());
          onChanged();
        } else {
          csvdataBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .csv.CSVData csvdata = 1;</code>
       */
      public Builder addAllCsvdata(
          java.lang.Iterable<? extends csv.csvproto.CSVData> values) {
        if (csvdataBuilder_ == null) {
          ensureCsvdataIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, csvdata_);
          onChanged();
        } else {
          csvdataBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .csv.CSVData csvdata = 1;</code>
       */
      public Builder clearCsvdata() {
        if (csvdataBuilder_ == null) {
          csvdata_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          csvdataBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .csv.CSVData csvdata = 1;</code>
       */
      public Builder removeCsvdata(int index) {
        if (csvdataBuilder_ == null) {
          ensureCsvdataIsMutable();
          csvdata_.remove(index);
          onChanged();
        } else {
          csvdataBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .csv.CSVData csvdata = 1;</code>
       */
      public csv.csvproto.CSVData.Builder getCsvdataBuilder(
          int index) {
        return getCsvdataFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .csv.CSVData csvdata = 1;</code>
       */
      public csv.csvproto.CSVDataOrBuilder getCsvdataOrBuilder(
          int index) {
        if (csvdataBuilder_ == null) {
          return csvdata_.get(index);  } else {
          return csvdataBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .csv.CSVData csvdata = 1;</code>
       */
      public java.util.List<? extends csv.csvproto.CSVDataOrBuilder> 
           getCsvdataOrBuilderList() {
        if (csvdataBuilder_ != null) {
          return csvdataBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(csvdata_);
        }
      }
      /**
       * <code>repeated .csv.CSVData csvdata = 1;</code>
       */
      public csv.csvproto.CSVData.Builder addCsvdataBuilder() {
        return getCsvdataFieldBuilder().addBuilder(
            csv.csvproto.CSVData.getDefaultInstance());
      }
      /**
       * <code>repeated .csv.CSVData csvdata = 1;</code>
       */
      public csv.csvproto.CSVData.Builder addCsvdataBuilder(
          int index) {
        return getCsvdataFieldBuilder().addBuilder(
            index, csv.csvproto.CSVData.getDefaultInstance());
      }
      /**
       * <code>repeated .csv.CSVData csvdata = 1;</code>
       */
      public java.util.List<csv.csvproto.CSVData.Builder> 
           getCsvdataBuilderList() {
        return getCsvdataFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          csv.csvproto.CSVData, csv.csvproto.CSVData.Builder, csv.csvproto.CSVDataOrBuilder> 
          getCsvdataFieldBuilder() {
        if (csvdataBuilder_ == null) {
          csvdataBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              csv.csvproto.CSVData, csv.csvproto.CSVData.Builder, csv.csvproto.CSVDataOrBuilder>(
                  csvdata_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          csvdata_ = null;
        }
        return csvdataBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:csv.CSVDataHouse)
    }

    // @@protoc_insertion_point(class_scope:csv.CSVDataHouse)
    private static final csv.csvproto.CSVDataHouse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new csv.csvproto.CSVDataHouse();
    }

    public static csv.csvproto.CSVDataHouse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<CSVDataHouse>
        PARSER = new com.google.protobuf.AbstractParser<CSVDataHouse>() {
      public CSVDataHouse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CSVDataHouse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CSVDataHouse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CSVDataHouse> getParserForType() {
      return PARSER;
    }

    public csv.csvproto.CSVDataHouse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_csv_CSVData_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_csv_CSVData_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_csv_CSVDataHouse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_csv_CSVDataHouse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024csv/CSVRecords.proto\022\003csv\"c\n\007CSVData\022\014" +
      "\n\004name\030\001 \002(\t\022\014\n\004city\030\002 \002(\t\022\017\n\007address\030\003 " +
      "\001(\t\022\013\n\003age\030\004 \002(\005\022\r\n\005city2\030\005 \001(\t\022\017\n\007zipco" +
      "de\030\006 \002(\t\"-\n\014CSVDataHouse\022\035\n\007csvdata\030\001 \003(" +
      "\0132\014.csv.CSVDataB\nB\010csvproto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_csv_CSVData_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_csv_CSVData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_csv_CSVData_descriptor,
        new java.lang.String[] { "Name", "City", "Address", "Age", "City2", "Zipcode", });
    internal_static_csv_CSVDataHouse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_csv_CSVDataHouse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_csv_CSVDataHouse_descriptor,
        new java.lang.String[] { "Csvdata", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
